name: Check

on: [push, pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: make check
      run: |
        # Install Go
        export PATH="$PATH:/usr/lib/go-1.14/bin"
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOBIN
        sudo apt-get -y install golang-1.14-go

        # Install goimports
        # golang-golang-x-tools is out of date, so use go get instead of apt
        go get golang.org/x/tools/cmd/goimports

        # Install Go linter
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

        make check

