name: Check

on: [ push, pull_request ]

jobs:
  build:
    name: Check
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Upgrade to Debian Testing to use latest software.
      run: |
        sudo apt-get -y install debian-archive-keyring
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
        sudo rm -rf /etc/apt/sources.list.d/
        echo "deb http://deb.debian.org/debian/ testing main" | sudo tee /etc/apt/sources.list

    - run: sudo apt-get update

    - run: sudo apt-get install -y golang-go golang-golang-x-tools make

    - name: make check
      run: |
        unset GOROOT
        # Install Go linter
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/go/bin v1.31.0
        export PATH=$PATH:~/go/bin

        make check
